import type { Metadata } from "next";

import "./globals.css";
import AuthContextProvider from "./api/auth/authcontext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       
      <AuthContextProvider>
        {children}
       </AuthContextProvider>
      </body>
    </html>
  );
}
